<?php

use App\Enums\TransactionType;
use App\Filament\App\Resources\Transactions\Pages\ManageTransactions;
use App\Models\Account;
use App\Models\Category;
use App\Models\Debt;
use App\Models\DebtPayment;
use App\Models\Transaction;
use App\Models\User;
use Filament\Actions\CreateAction;
use Filament\Actions\ExportAction;
use Filament\Actions\Exports\Enums\ExportFormat;
use Filament\Actions\Exports\Models\Export;
use Filament\Actions\Testing\TestAction;
use Illuminate\Support\Facades\Storage;
use Livewire\Livewire;

it('records an expense and lowers the account balance', function () {
    $book = actingInBook(User::factory()->create());
    $account = Account::factory()->for($book)->create(['initial_balance' => 100_000]);
    $category = $book->categories()->ofType(TransactionType::Expense)->first();

    Livewire::test(ManageTransactions::class)
        ->callAction(CreateAction::class, data: [
            'type' => TransactionType::Expense->value,
            'transaction_date' => '2026-09-01',
            'account_id' => $account->id,
            'category_id' => $category->id,
            'amount' => 35_000,
            'description' => 'Makan siang',
        ])
        ->assertHasNoFormErrors();

    expect($book->transactions()->sole())
        ->account_id->toBe($account->id)
        ->category_id->toBe($category->id)
        ->amount->toBe('35000.00')
        ->and($account->fresh()->current_balance)->toBe('65000.00');
});

it('rejects accounts and categories that belong to another book', function () {
    $foreignAccount = Account::factory()->create();
    $foreignCategory = Category::factory()->expense()->create();
    $book = actingInBook(User::factory()->create());

    Livewire::test(ManageTransactions::class)
        ->callAction(CreateAction::class, data: [
            'type' => TransactionType::Expense->value,
            'transaction_date' => '2026-09-01',
            'account_id' => $foreignAccount->id,
            'category_id' => $foreignCategory->id,
            'amount' => 10_000,
        ])
        ->assertHasFormErrors(['account_id', 'category_id']);

    expect($book->transactions()->count())->toBe(0);
});

it('rejects a category whose type does not match the transaction', function () {
    $book = actingInBook(User::factory()->create());
    $account = Account::factory()->for($book)->create();
    $incomeCategory = $book->categories()->ofType(TransactionType::Income)->first();

    Livewire::test(ManageTransactions::class)
        ->callAction(CreateAction::class, data: [
            'type' => TransactionType::Expense->value,
            'transaction_date' => '2026-09-01',
            'account_id' => $account->id,
            'category_id' => $incomeCategory->id,
            'amount' => 10_000,
        ])
        ->assertHasFormErrors(['category_id']);
});

it('only lists transactions of the current book', function () {
    $foreignTransaction = Transaction::factory()->create();
    $book = actingInBook(User::factory()->create());
    $ownTransaction = Transaction::factory()->for($book)->create();

    Livewire::test(ManageTransactions::class)
        ->assertCanSeeTableRecords([$ownTransaction])
        ->assertCanNotSeeTableRecords([$foreignTransaction]);
});

it('hides edit and delete for transactions generated by a debt installment', function () {
    $book = actingInBook(User::factory()->premium()->create());
    $debt = Debt::factory()->for($book)->create();
    $payment = DebtPayment::factory()->for($debt)->for(Account::factory()->for($book))->create();
    $manualTransaction = Transaction::factory()->for($book)->create();

    Livewire::test(ManageTransactions::class)
        ->assertActionHidden(TestAction::make('edit')->table($payment->transaction))
        ->assertActionHidden(TestAction::make('delete')->table($payment->transaction))
        ->assertActionVisible(TestAction::make('edit')->table($manualTransaction));
});

it('offers only CSV export to free users and adds Excel for premium users', function (bool $isPremium, array $expectedFormats) {
    actingInBook($isPremium ? User::factory()->premium()->create() : User::factory()->create());

    Livewire::test(ManageTransactions::class)
        ->assertActionExists(
            TestAction::make('export')->table(),
            fn (ExportAction $action): bool => $action->getFormats() === $expectedFormats,
        );
})->with([
    'free' => [false, [ExportFormat::Csv]],
    'premium' => [true, [ExportFormat::Csv, ExportFormat::Xlsx]],
]);

it('exports only the transactions of the current book', function () {
    Storage::fake('local');
    Transaction::factory()->count(2)->create();
    $book = actingInBook(User::factory()->create());
    Transaction::factory()->count(3)->for($book)->create();

    Livewire::test(ManageTransactions::class)
        ->callAction(TestAction::make('export')->table());

    expect(Export::sole()->total_rows)->toBe(3);
});
